# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/movie_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
# If you have a password:
# spring.data.redis.password=yourpassword
spring.data.redis.connect-timeout=2000
spring.data.redis.timeout=100

# Tells Spring to run data.sql on every startup
spring.sql.init.mode=always

# Defer data initialization until after JPA schema creation
spring.jpa.defer-datasource-initialization=true

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Java 21 Performance (Virtual Threads)
spring.threads.virtual.enabled=true

# Logging for Debugging
logging.level.org.hibernate.SQL=DEBUG